### ISSUE TITLE
kernel module params

### ISSUE THREAD

**Issue by mkalten** [floe/surface-2.0#12]
what would you think about adding two kernel module options,
that should allow to deactivate either the v4l2 or the xinput part of the driver?
usually I always need to issue "xinput float" in order to deactivate the native touch,
a kernel option at startup would come handy in this case ...

**Comment by floe** [comment]
Good idea, I was thinking about this at some point, too, but forgot again :-)

**Comment by mkalten** [comment]
I added a stub for the kernel params by setting two bools in my fork, but I am wondering if it's enough just not to export the two respective devices, or actually disable their handling everywhere ...

**Comment by floe** [comment]
If there's a way to disable the input device on boot (and I think that should be possible with udev somehow), then it's perhaps not worth the effort of another kernel patch.

**Comment by mkalten** [comment]
OK you are right, an according udev rule seems the way to go ... I'll give it a try!
