### ISSUE TITLE
camera control

### ISSUE THREAD

**Issue by mkalten** [floe/surface-2.0#13]
now that we have a stabilized the v4l2 driver, we should think about implementing the more advanced features, such as a control of the camera exposure etc. if possible.
could you maybe point me how you did the USB sniffing on windows, so I can see by myself if there are any more hidden device configuration registers?

**Comment by floe** [comment]
The basic process was:
  * Boot Linux
  * Load usbmon module on host Linux
  * Start old Windows installation in Virtualbox VM
  * Attach "Microsoft Vision Input Processor" to VM
  * Run wireshark to capture USB data

**Comment by mkalten** [comment]
thanks, I found another USB sniffer which works directy from within windows,
but since this is new territory for me, I still need to figure out waht all that data actually does ;)

**Comment by floe** [comment]
Found anything interesting so far?

**Comment by mkalten** [comment]
nope, still no idea where to start and a bit to shy to try things, considering your earlier bricking experience ... but eventually we'll find something I am sure ;)

**Comment by floe** [comment]
Can you upload your captured data somewhere, with some annotations where you changed settings?

**Comment by mkalten** [comment]
@floe I uploaded some USB capture data from the calibration process here https://github.com/floe/surface-2.0/issues/14

**Comment by floe** [comment]
Mostly overlaps with #14, discussion continued there.
