### ISSUE TITLE
calibration & sensor control

### ISSUE THREAD

**Issue by mkalten** [floe/surface-2.0#14]
although this is not a major showstopper for reactivision, it would be nice if we also provide a userspace program for calibrating the sur40 sensor. windows provides such functionality, using that double sided, one side black, one side white calibration sheet. this calibration step removes some image noise, providing a generally cleaner camera image. unfortunately this calibration is apparently lost, when unplugging the device, so it has to be redone from time to time. maybe another USB sniffing job during the windows calibration task will reveal some more details for the device configuration, since that calibration data eventualy has to be stored somewhere in the device firmware I guesss ...

**Comment by floe** [comment]
Hmm, I don't remember seeing anything related in my old USB dumps, I would have assumed that this is done in software... OTOH, then it probably wouldn't influence the touch detection. I never actually captured the calibration process IIRC, should probably do that sometime :-)

**Comment by mkalten** [comment]
Well, I did the calbration once with a selfmade sheet, and it cleaned up the overall sensor noise a bit. After I unplugged the SUR40 one day, the calibration was lost though, which made me think the the calibration data must be stored in some kind of volatile memory in the firmware. So this could be another  way to find out more about the device configuration registers I hope ...
In any case, since reacTIVision does its own image equalization, which also fets rid of fatty finger stains etc. this is not really a showstopper at the moment, but definitely a nice to have feature.

**Comment by mkalten** [comment]
here is the USB sniffing dump from a complete calibration session, 
from what I can tell, the type and format of data is signicantly different ...

[calib_dump.zip](https://github.com/floe/surface-2.0/files/317054/calib_dump.zip)

**Comment by floe** [comment]
That's very interesting, AFAICT:
  * 01_before_calib: just regular touchpoint data
  * 02_white_calib: 2 frames of "plain" video data input, followed by ~ 244*512 bytes of data _output_
  * 03_save_calib: totally unknown, but also mostly data input from the device

**Comment by mkalten** [comment]
yo, that's what I guessed so far as well,
would be interesting to find out about the control commands though,
in order to trigger the calibration ... any hint?

**Comment by floe** [comment]
What I could see in 02_white_calib was data being written _to_ the video device; it's always blocks of 2048 bytes with a small header: `00 c8 10 05 00 08 00 00` <- offset 0x0510c800, size 0x00000800

However, almost all of the data written _to_ the device seems to be zero. Not quite sure yet what's going on...

**Comment by floe** [comment]
I've collected a complete trace of a calibration run; my current notes are in `calibration_sequence.md` in the main repository. Will have to re-try with the original calibration sheet, because mine is currently mis-calibrated and also doesn't reset itself after a complete power-off...

**Comment by mkalten** [comment]
I just made my own sheet with a plain white and black opaque cardboard sheet of the right size glued together. Once I saw the actual calibration sheet, it's not much different from that.

Also on my side I haven't been able to reset the calibration even after unplugging the device, that's why we actually should find out the according control command to properly do that ;)

**Comment by floe** [comment]
I've played around a bit with the USB sequence captured during calibration. There seems to be an internal 48 byte register memory, and some registers definitely control the sensor gain, see notes here: https://github.com/floe/surface-2.0/blob/master/config_memory.md

**Comment by floe** [comment]
JFYI, I've found that `SUR40CalibrationTool.exe` is a C# program, and when you disassemble it with ILSpy, you get an _insane_ amount of information about the calibration process and the device internals :-D

Some of that is already in the `userspace` folder, but completely untested. Updates hopefully next week.

**Comment by floe** [comment]
- [ ] IR backlight intensity control
- [ ] sensor blacklevel & gain control
- [ ] disable image corrector

**Comment by mkalten** [comment]
another TODO:
- [ ] read control values from sensor

**Comment by mkalten** [comment]
I just added an (empty) method to disable the image corrector,
and currently use the V4L "backlight compensation" switch for testing.

**Comment by floe** [comment]
For the record, what I know about the image corrector is here: https://github.com/floe/surface-2.0/blob/master/userspace/surface.c#L122-L132

I'll push a bit of sample code later today (hopefully).

**Comment by mkalten** [comment]
just wanted to add for other readers, that the current image controls already are *amazing*
I adjusted the new controls on the SUR40, and we now can tune the image quality just to the sweet spot, even after changing the environmental light conditions! What I found is to keep the IR (brightness) level generally to the maximum and play with the gain and contrast (blacklevel) settings, until the background noise disappears and the exposure seems right ...

**Comment by mkalten** [comment]
just to confirm, the image corrector switch now also works!
as expected the overall uniformity decreases significantly,
although the thresholder still gets a usable image from it ...

**Comment by floe** [comment]
Awesome :-) Any noticeable difference in frame rate or latency?

**Comment by mkalten** [comment]
well, the frame rate is obviously the same 60fps,
and regarding the latency I can't really tell without an actual measurement.
