### ISSUE TITLE
VFL_TYPE_TOUCH_SENSOR

### ISSUE THREAD

**Issue by mkalten** [floe/surface-2.0#17]
not an issue, just a heads up for a recent development from v4l2:

http://www.gossamer-threads.com/lists/linux/kernel/2465840

the sur40 driver is now of VFL_TYPE_TOUCH_SENSOR

**Comment by mkalten** [comment]
OK, I see that you are already on the topic:
https://lkml.org/lkml/2016/6/22/332

In general it wouldn't be a big problem though to consider such a device type in the reacTIVision V4L2 driver, provided that the data from the other devices from that class may be of interest for image analysis.

**Comment by mkalten** [comment]
@floe looking at how the discussion and possible solutions are developing, I'd suggest to exclude SUR40 from these alternative device types and pixel formats or device names, since all three attributes are actually used to enumerate suitable V4L2 camera devices.

**Comment by floe** [comment]
OK, I think there's 3 separate changes:
 * the pixel format. I think that's not something we should change, because it _is_ greyscale image data.
 * the device type (VFL_TYPE_TOUCH). Not a big difference AFAICT, from what I could see portvideo looks for V4L2_CAP_VIDEO_CAPTURE and that remains unchanged.
 * the device name. That's the most sensible change IMHO - can you manually specify the device name in rTV?

**Comment by mkalten** [comment]
well, in general I can adapt everything to those changes, even the pixelformat if this is 8bit grayscale anyway ... portvideo now enumerates all available devices and maintains internal IDs for compatible ones, so you can't specify a device name directly. but in any case I could also scan for the new device type.

in general I'd only include SUR40 into this new classification if the other devices there potentially may be useful for reactivision (or similar software) too

**Comment by floe** [comment]
I can understand the argument that you don't want this kind of V4L2 device to show up in Skype or similar software, hence the different device name. A workaround would be to add a symlink back to /dev/videoX, but that's a bit of a hack IMHO...

**Comment by mkalten** [comment]
In general I could see possible use cases for streaming the surface content via Skype as well,
but as I said I don't see a big problem to adapt portvideo to the eventual changes neither ...

**Comment by mkalten** [comment]
@floe looking at the linux-media mailing list, somehow I have the impression the developers have gone wild on the sur40 driver ... many weird changes, while our relevant patches haven't been considered yet apparently. anyhow, I'll give everything a try once the dust has settled ...

**Comment by floe** [comment]
Our patches seem to have been merged recently...

**Comment by mkalten** [comment]
wonderful, as I see at least the two important fixes already made it into 4.4, 4.7 and 4.8
