### ISSUE TITLE
lower frame rate in kernel 4.8.x

### ISSUE THREAD

**Issue by mkalten** [floe/surface-2.0#20]
I just upgraded to Ubuntu 16.10 which comes with a default 4.8 kernel.
Unfortunately I am observing a reduced frame rate of around 52fps with the default kernel, as well as with a custom built sur40 kernel module. Using the earlier 4.4 kernel on the same system still results in a stable 60fps.

Maybe you can ask on the linux-media list what could be the cause for this decrease?
In the meanwhile I'll try tweaking the kernel module code ...

**Comment by floe** [comment]
Hm, strange... maybe something in the input framework (esp. `input_polldev`) has changed?

**Comment by mkalten** [comment]
my (hopefully not too esoteric) hypothesis is that our earlier reduction of the poll interval to 1ms was just a workaround for a totally different problem, which probably now emerged again through some external changes or regressions. I'll have a look at other drivers if there are some relevant changes ...

**Comment by mkalten** [comment]
hi @floe, I just upgraded to kernel 4.9 and that problem seems to have disappeared, so I guess this just has been a 4.8 related problem. regarding the significant device type and pixelformat changes in 4.9, I can confirm that reacTIVision still works, although I had to place a symbolic link to /dev/video0 from /dev/v4l-touch0 for the time being ...
