### ISSUE TITLE
libusb-1.0

### ISSUE THREAD

**Issue by mkalten** [floe/surface-2.0#21]
while doing the windows port, I just noticed that the user space code is still using libusb0.
what would be the effort to port surface.cpp to libusb-1.0? probably a bit of search and replace ;)
maybe this would also resolve the performance bottleneck in user space ...

**Comment by floe** [comment]
Good point, libusb-0.1 is from ~ 2009 :-) It's apparently not quite the same API, so a bit of rewrite needed, but there's a compatibility layer here: https://git.libusb.org/?p=libusb-compat-0.1.git;a=blob;f=libusb/core.c;h=2dd1b5f09bffe6cc2aa2cc806a84ebdf05c2c605;hb=HEAD;js=1

**Comment by mkalten** [comment]
ok, just tried to compile everything with libusb-compat, it obviously works.
still an actual port to the new API should be quite straightforward I guess ...

**Comment by mkalten** [comment]
I had a look at it, the only relevant functions with significant changes are usb_control_msg, usb_bulk_read and usb_bulk_write ... the rest is basically just renaming the functions and handles as far as I can tell.

**Comment by mkalten** [comment]
done! everything seems to work as expected.
I tested test & view as well as my tuio tool ...
