### ISSUE TITLE
Patches for kernel driver

### ISSUE THREAD

**Issue by floe** [floe/surface-2.0#22]
ToDo list of patches to be submitted for inclusion into kernel:

- [x] bugfix to avoid sending raw blobs as touches to input layer (-> linux-input)
- [x] V4L2 camera controls (brightness, gain, contrast) (-> linux-media)
- [x] module parameter to directly set control values on load (-> linux-media)

**Comment by mkalten** [comment]
added the missing vsvideo and irlevel module parameters

**Comment by mkalten** [comment]
I added the module parameters ...

**Comment by floe** [comment]
BTW: Android-x86 7.1 is now running nicely from a "userspace" install on the Linux partition. Is there a howto for compiling a different kernel module for the Android kernel?

**Comment by floe** [comment]
https://github.com/floe/surface-2.0/blob/master/kernel/sur40.c#L424 <- would it be better to skip everything that's not SUR40_TOUCH?

**Comment by mkalten** [comment]
probably yes, I also noticed false positives for bytetags, but didn't want to generally define them as palm. so probably the most correct way would be to ignore tags until there is a dedicated type.

**Comment by mkalten** [comment]
skip also done ...

**Comment by mkalten** [comment]
btw, did you use the 64bit or 32bit android package?

**Comment by floe** [comment]
32 bit, IIRC...

**Comment by mkalten** [comment]
patch #1 made it into linux-next for 4.14 a week ago:
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/log/?h=next-20170719&qt=grep&q=sur40
