### ISSUE TITLE
mainline kernel updates

### ISSUE THREAD

**Issue by mkalten** [floe/surface-2.0#5]
hi, there have been some significant updates to the mainline kernel version of the sur40 driver:

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/diff/drivers/input/touchscreen/sur40.c?id=v4.6-rc4&id2=v4.4

I just tested this kernel installing it from the ubuntu mainline ppa, and everything seems to work fine,
there haven't been any of those crashes so far, when closing the v4l2 device ...

Maybe you could update your repository from the mainline kernel, since I also have some minor fixes for a more complete v4l2 device configuration, such as a dummy method for framerate (vidioc_s_parm/vidioc_g_parm ) configuration

**Comment by floe** [comment]
Good to know, thanks - I'll probably drop the 3.16 backport and just keep a standalone version of the kernel driver in here. Did you test with 4.6 or 4.4?

**Comment by mkalten** [comment]
I tested it with Kernel 4.6rc4 since the included changes don't work with earlier versions, so I guess that's the reason for those updates. As I said, so far I didn't experience any crashes or other kernel log error messages with this version, which seems to be a sign for external improvements as well.

If you want to test it quickly, you can easily install the current deb packages from the mainline kernel ppa:
http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.6-rc4-wily/ (works also with xenial, which I am running)

And yes, I'd also suggest to keep this repository in sync with the mainline kernel development, maybe by moving the current master into a separate branch, and then merge the mainline code into the master.

As I said, I'd also have some minor updates, that improve the compatibility with the v4l2 configuration,
which I then could create a pull request for, and which then eventually could make it into kernel 4.7 if we are lucky ...

**Comment by floe** [comment]
OK, not too much arcane git-hackery was required :-)
* master branch is now most recent in-kernel version (as of v4.6-rc4).
* backport-3.16 contains old version suitable for v3.16
I'll leave the issue open until your patch has been resolved.

**Comment by mkalten** [comment]
I hope you didn't submit your patch yet,
since I just made another small update,
which should avoid possible warnings,
to keep the maintainers happy

**Comment by floe** [comment]
Thanks, merged - I'll try to submit the patch next weekend.

**Comment by mkalten** [comment]
ok, by the way ...  after some extended testing I have been seeing that known kernel dump from time to time again, although I still didn't experience one of those nasty freezes yet when closing the v4l2 device.
let's keep the fingers crossed ...
