### ISSUE TITLE
linux 4.4.x backport

### ISSUE THREAD

**Issue by mkalten** [floe/surface-2.0#9]
I also created a branch with a working backport for the longterm Linux 4.4 kernel,
which is also used in the current Ubuntu 16.04 LTS release. 
I have no idea though how to push a branch from my fork to your repository ...

Probably it's also worth a try to submit a patch to the maintainer of this kernel.

**Comment by floe** [comment]
I think when I create a branch with the same name, then you can create a PR for that. How should I call it?

**Comment by floe** [comment]
(probably backport-4.4)?

**Comment by mkalten** [comment]
yes, my branch is called backport-4.4 too ....
I guess once you created that too, I can simply issue a pull request

**Comment by floe** [comment]
OK, created.
